import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Cascadia_Mono } from 'next/font/google';
import { Footer, Header, Main } from '@/layout';
import './globals.css';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

const cascadiaMono = Cascadia_Mono({
  variable: '--font-cascadia-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Cluvone',
  description: 'Generated by Cluvone',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="ko" className={`${pretendard.variable} ${cascadiaMono.variable} antialiased`}>
      <body className="min-h-screen">
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
