import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Cascadia_Mono } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { cn } from '@/lib';
import '@/styles/globals.css';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

const cascadiaMono = Cascadia_Mono({
  variable: '--font-cascadia-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Cluvone',
  description: 'Generated by Cluvone',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="ko" className={cn('antialiased', pretendard.variable, cascadiaMono.variable)} suppressHydrationWarning>
      <body className="bg-background text-foreground max-h-screen min-h-svh">
        <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
